### ISSUE TITLE
how to resolve this error?

### ISSUE THREAD

**Issue by shivammishraiith** [vtsuperdarn/davitpy#345]
Populating the interactive namespace from numpy and matplotlib
Traceback (most recent call last):

  File "/Users/satyammishra/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-d2d2a7e51e55>", line 5, in <module>
    from davitpy import pydarn

  File "/Users/satyammishra/.local/lib/python3.6/site-packages/davitpy-0.8-py3.6-macosx-10.7-x86_64.egg/davitpy/__init__.py", line 617
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by suraj44** [comment]
Use Python 2.7 and the error won't show up

**Comment by ksterne** [comment]
Davitpy hasn't been updated or tested well with python3.  If you uses python2.7 does this solve your issue @shivammishraiith?
